# One-off: download the (variable) Google Fonts woff2 files App uses and
# generate a local fonts.css, so the app no longer depends on the Google Fonts
# CDN at runtime. Inter/JetBrains Mono are variable fonts — one file per subset
# covers the whole weight range, so we emit a single ranged @font-face each.
$ErrorActionPreference = 'Stop'
$ua = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0 Safari/537.36'
$cssUrl = 'https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;750;800&family=JetBrains+Mono:wght@400;500;600;700&display=swap'

$uiCss    = 'd:\GitHub\DevCenter\app\ui\css'
$fontsDir = Join-Path $uiCss 'fonts'
if (Test-Path $fontsDir) { Remove-Item $fontsDir -Recurse -Force }
New-Item -ItemType Directory -Force -Path $fontsDir | Out-Null

$keepSubsets = @('latin', 'latin-ext')
# Requested weight range per family (matches the css2 request above).
$ranges = @{ 'Inter' = '400 800'; 'JetBrains Mono' = '400 700' }

$css = (Invoke-WebRequest -Uri $cssUrl -Headers @{ 'User-Agent' = $ua } -UseBasicParsing).Content
$rx  = [regex]'/\*\s*(?<subset>[\w-]+)\s*\*/\s*@font-face\s*\{(?<body>[^}]*)\}'

# Collect one entry per (family, subset) — variable fonts return the same file
# URL for every requested weight, so we dedupe.
$seen = @{}
$entries = @()
foreach ($m in $rx.Matches($css)) {
  $subset = $m.Groups['subset'].Value
  if ($keepSubsets -notcontains $subset) { continue }
  $body = $m.Groups['body'].Value
  $fam  = ([regex]"font-family:\s*'([^']+)'").Match($body).Groups[1].Value
  $key  = "$fam|$subset"
  if ($seen.ContainsKey($key)) { continue }
  $seen[$key] = $true
  $entries += [pscustomobject]@{
    Family  = $fam
    Subset  = $subset
    Url     = ([regex]'src:\s*url\(([^)]+)\)').Match($body).Groups[1].Value
    Unicode = ([regex]'unicode-range:\s*([^;]+)').Match($body).Groups[1].Value.Trim()
  }
}

$out = New-Object System.Text.StringBuilder
[void]$out.AppendLine('/* Self-hosted fonts (generated by scripts/fetch-fonts.ps1) — replaces the Google Fonts CDN. */')
foreach ($e in $entries) {
  $famSlug = ($e.Family -replace '\s+', '')
  $file    = "$famSlug-$($e.Subset).woff2"
  Invoke-WebRequest -Uri $e.Url -Headers @{ 'User-Agent' = $ua } -OutFile (Join-Path $fontsDir $file) -UseBasicParsing
  $weight  = $ranges[$e.Family]
  [void]$out.AppendLine('@font-face {')
  [void]$out.AppendLine("  font-family: '$($e.Family)';")
  [void]$out.AppendLine('  font-style: normal;')
  [void]$out.AppendLine("  font-weight: $weight;")
  [void]$out.AppendLine('  font-display: swap;')
  [void]$out.AppendLine("  src: url(fonts/$file) format('woff2');")
  [void]$out.AppendLine("  unicode-range: $($e.Unicode);")
  [void]$out.AppendLine('}')
  Write-Host ("saved {0,-26} {1}" -f $file, $e.Url)
}

[IO.File]::WriteAllText((Join-Path $uiCss 'fonts.css'), $out.ToString())
Write-Host ("`nGenerated fonts.css with {0} @font-face rules." -f $entries.Count) -ForegroundColor Green
Get-ChildItem $fontsDir | Select-Object Name, @{N='KB';E={[math]::Round($_.Length/1KB,1)}} | Format-Table -AutoSize
